### ISSUE TITLE
Error when adding ofxPiMapper to an existing project

### ISSUE THREAD

**Issue by pauloguerraf** [kr15h/ofxPiMapper#113]
Hi,

I am trying to use ofxPiMapper in a project, but when I add it as addon to a project I keep getting the following errors:

ofxpimapper\src\surfaces\gridwarpsurface.cpp(63): error C4716: 'ofx::piMapper::GridWarpSurface::setGridRows': must return a value
ofxpimapper\src\surfaces\gridwarpsurface.cpp(68): error C4716: 'ofx::piMapper::GridWarpSurface::setGridCols': must return a value
ofxpimapper\src\application\settingsloader.cpp(238): error C4716: 'ofx::piMapper::SettingsLoader::save': must return a value

Any help to solve will be greatly appreciated. 

Best,

Paulo

**Comment by kr15h** [comment]
What is the platform you are building it on? And the version of openFrameworks?

**Comment by pauloguerraf** [comment]
Hi, I am using openFrameworks 0.9.8. and building for Windows.


On Jun 6, 2017 2:33 AM, "Krisjanis Rijnieks" <notifications@github.com>
wrote:

What is the platform you are building it on? And the version of
openFrameworks?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kr15h/ofxPiMapper/issues/113#issuecomment-306406025>,
or mute the thread

**Comment by kr15h** [comment]
Could you post more of the error content you got?

**Comment by pauloguerraf** [comment]
Here is a screenshot of what I get... I added ofxPiMapper and
ofxXmlSettings to the project addons, and in ofApp.h I added these 2 lines
#include "ofxXmlSettings.h"
#include "ofxPiMapper.h"

the project was working fine before that.

[image: Inline image 2]

On Tue, Jun 6, 2017 at 6:36 AM, Krisjanis Rijnieks <notifications@github.com

**Comment by pauloguerraf** [comment]
got it working

added return _gridRows in line 63
added return _gridCols in line 68
and added a boolean return depending on the result of xml.save in line 238

**Comment by kr15h** [comment]
Good. Usually these are warnings with other compilers.
