### ISSUE TITLE
ofxOmxplayer playlist feature

### ISSUE THREAD

**Issue by magdesign** [kr15h/ofxPiMapper#116]
How can ofxPiMapper compile a playlist version of ofxOmxplayer ?

Or in other words, how would it be possible to make ofxPiMapper playing all videos named like:
01_video.mp4, 02_video.mp4..... in a Playlist manner ?

`https://github.com/jvcleave/ofxOMXPlayer/blob/master/example-playlist/src/ofApp.cpp`

**Comment by kr15h** [comment]
Will look into that.

**Comment by magdesign** [comment]
Any news on this?

**Comment by kr15h** [comment]
For now I would suggest you to build a custom source for this. It would be not that straightforward to have this kind of functionality in ofxPiMapper.
