### ISSUE TITLE
last openframeworks git

### ISSUE THREAD

**Issue by pietrondo** [kr15h/ofxPiMapper#118]
Hi it is working ofxPimapper with last git of openframeworks?
I have archlinux and 0.9.8 have some problem with it.

thx

**Comment by kr15h** [comment]
No, I decided to develop only against the current stable (0.9.8) version.

**Comment by toughvj** [comment]
Hi there, so what is the best of version to build? I'm running Raspbian Stretch on RPI3.
regards!

**Comment by kr15h** [comment]
Hi! The one hat the master branch is at currently.

**Comment by toughvj** [comment]
Thank's for reply!
I mean openframeworks :) You also?
When using (0.9.8) during compilation a receive many notifications about none return statements and unused variables, ignore this or add return statements and remove variables?

**Comment by kr15h** [comment]
Yes, 0.9.8 is the current stable version. You can ignore the warnings. Errors are what matter.
