### ISSUE TITLE
USB and MediaSever

### ISSUE THREAD

**Issue by toughvj** [kr15h/ofxPiMapper#119]
Hi there,
when trying to use medias on usb it seems that MediaServer add for example file test.mp4 as usb0test.mp4, file is not loaded to surface, OMXPlayer calls error loading file and PiMapper saves to xml file usb0test.mp4. When running one more time it seems that MediaServer is looking for file usb0test.mp4 in data/sources/videos.

Compiled on OF 0.9.8 Raspbian Stretch, nothing changed in source code.

**Comment by kr15h** [comment]
Ok. Will check it out!
