### ISSUE TITLE
new addons to install in openframeworks for example_server

### ISSUE THREAD

**Issue by pietrondo** [kr15h/ofxPiMapper#132]
Hi!
thx for the big improvement!
so we need to install this https://github.com/jeffcrouse/ofxJSON
on our openframeworks addons folder?
thx

**Comment by kr15h** [comment]
Yes, since I chose to use JSON for data transfer. Maybe I will change it later, but for now it makes things a lot easier.

**Comment by pietrondo** [comment]
ok. can you add it in the readme?

**Comment by kr15h** [comment]
Will do

**Comment by pietrondo** [comment]
with this version.. https://github.com/PTS93/ofxJSON/tree/patch-1
I can compile the client on my last archlinux gcc 7 and the last openframeworks

**Comment by kr15h** [comment]
OK, done ea851c83b19ea0ac257dfcb6d46bf8a34e0258c6

**Comment by pietrondo** [comment]
you need also to do: git checkout patch-1
