### ISSUE TITLE
Bugs in: example_remote-client 

### ISSUE THREAD

**Issue by magdesign** [kr15h/ofxPiMapper#140]
I figured out following bugs:

When creating a new surface (quad, circle or triangle) from the remote client, several things do not work right yet:
- The resize handle does not seem to work. Workaround = using +/- keys or close client and open it again.
- Moving the corners in triangle does not work. Workaround = close client and open it again.

And:
- colors of videos are rendered in green as soon as client connects. Workaround = restart mapper.
- no FBO sources selectable with TAB key.

My test scenario:
- client: Ubuntu 17.10, of_0.9.8
- server: RPi3, jessie, of_0.9.8, 1920x1080, 492MB allocated memory (sudo vcdbg reloc)

**Comment by hgshoggins** [comment]
I confirm the greenish rendering on the server as soon as the client connects.

**Comment by pietrondo** [comment]
same problem.... greenish rendering

**Comment by kr15h** [comment]
Could be because I am not using `ofPushStyle()` and `ofPopStyle()` when setting color for the green status connection dot. Will take a look.

**Comment by kr15h** [comment]
Fixed 67609da29be628913a79997e85cace1718501529

**Comment by pietrondo** [comment]
THX now It works!!

Il giorno mer 5 dic 2018, 22:15 Krisjanis Rijnieks <notifications@github.com>
ha scritto:
