### ISSUE TITLE
Circle doesn't mask buffer

### ISSUE THREAD

**Issue by aubergene** [kr15h/ofxPiMapper#153]
I'm trying to use the circle surface, and I want to layer it on top of other surfaces however it doesn't appear to mask the buffer correctly, it makes anything outside of the circle black, when it should be transparent. Is this a bug or just something I'm doing wrong? Thanks

edit: Also in mode 2 where you chose the crop, for a triangle, you get a triangle space to choose the crop, but for a circle you still get a rect, so it feels like perhaps that is where the issue is.

<img width="1192" alt="screenshot 2018-12-10 at 23 45 47" src="https://user-images.githubusercontent.com/1710/49862298-c80e5f00-fdf5-11e8-81db-506c1f00551d.png">

**Comment by kr15h** [comment]
Hi! The circle surface was a contribution and it is basically the same quad surface with a mask on it. I will take a look, maybe there is a way to make the black part transparent.

**Comment by aubergene** [comment]
Thanks that would be great. Yes, that makes sense to just have a general way to mask. I'm pretty new to c++ and OF but tried this without luck, but I can continue to play around

```c++
fbo->getTexture().setAlphaMask(mask.getTexture());
```

**Comment by c-mendoza** [comment]
Way late to this party, but I just submitted a PR that should fix this. FYI the CircleSurface was a total rush job and my intention was to keep working on it on a separate repo. Part of why it was done with a mask was to :

1. Not have to modify the texture mapping and perspective mapping widgets of the app.
2. Make mapping more straightforward for circles (if you have an ellipse shape that you are distorting you might not end up with an actual perspective warped circle).

So it was 100% a hack! Anyways, hope this helps someone.

**Comment by magdesign** [comment]
@c-mendoza: Thanks for looking into this.
Unfortunately your fix does not build, see comment on pull request.
