### ISSUE TITLE
PiMapper -  openFramworks v0.10.1 - PocketVJ

### ISSUE THREAD

**Issue by slagteriet** [kr15h/ofxPiMapper#159]
Hi Im running a build of the great pocketVJ project and wanted to add PiMapper to extend the greatness.

I got the latest version of openFrameworks running v0.10.1 combine with this install guide. [(link)](https://openframeworks.cc/setup/raspberrypi/raspberry-pi-getting-started/)

I then followed this GitHub instructions [link here](https://ofxpimapper.com/pages/github-instructions/)

But seems not to be working..  ?

> From the guide in link above..
> Checkout the stable version of ofxOMXPlayer.
> cd /home/pi/openFrameworks/addons/ofxOMXPlayer
> git checkout 0.9.0-compatible

**Comment by kr15h** [comment]
Could be they are a bit outdated. Let me take a look... ; ]

**Comment by kr15h** [comment]
```
cd /home/pi/${OFX_DIR}/addons/ofxOMXPlayer
./install_depends.sh

```

**Comment by kr15h** [comment]
```
git checkout master
cd /home/pi/${OFX_DIR}/addons/ofxOMXPlayer
./install_depends.sh
```

Will update the instructions on website.

**Comment by slagteriet** [comment]
Thank you @kr15h Will try it.

**Comment by kr15h** [comment]
Then there is this CI file that I use to make automated builds: https://gitlab.com/kriwkrow/pimapper/blob/master/ci/rpi/pi-gen/stagePiMapper/00-install-opm/00-run.sh Maybe you find something useful there as well.

**Comment by slagteriet** [comment]
@kr15h did it work ? :)

**Comment by kr15h** [comment]
Well, it works with the automatic build. 
You can download the image file (artifacts) here https://gitlab.com/kriwkrow/pimapper/tags/v1.0.0
or from the ofxpimapper.com website https://ofxpimapper.com

**Comment by kr15h** [comment]
I am building with the master branch of openFrameworks, and latest version of Raspbian
