### ISSUE TITLE
what is the command line to open ofxpimapper

### ISSUE THREAD

**Issue by balejandrovb** [kr15h/ofxPiMapper#177]
my program closed and no longer opens, what is the command line to execute it. I already tried restarting the RPb3 but it doesn't work
... please help me

**Comment by kr15h** [comment]
Hi. Sorry to read. What was the last thing you did when it was still open?

**Comment by balejandrovb** [comment]
i restarted because i introduced USB for new sources. i dont want to reinstall the .img , because i already have the perfect callibration. is there any way to open by command line? thanks for ur attention

**Comment by kr15h** [comment]
So yeah it might be that Pi Mapper has problems playing back some of your videos. Place an empty file with the name `PIMAPPER_DELETE_SOURCES` on the USB drive and reboot. Then double-check your sources to be HD 720p resolution and 30fps or so. Use `baseline` H264 setting when encoding. Best results with this so far.

**Comment by kr15h** [comment]
Another thing could be that the settings file got broken and needs to be restored. Anyhow one could check it with `sudo systemctl status pimapper`
