### ISSUE TITLE
Pi zero 2

### ISSUE THREAD

**Issue by mhellar** [kr15h/ofxPiMapper#186]
Hi, I love ofxpimapper! Wondering if it can run on the new pi zero 2? Pi 3's are getting had to find! Thanks!

**Comment by Sebizarro** [comment]
Hey, i've already tried by just changing the SD card, but it didn't work. Using a Pi3A+ and it works.

**Comment by kr15h** [comment]
Hi! No, it does not work with the Pi4 and PiZero 2 yet.
