### ISSUE TITLE
Crashing when loading omxPlayer source repeatedly

### ISSUE THREAD

**Issue by kr15h** [kr15h/ofxPiMapper#19]
After loading the video the second time on RPi app crashes and this is the output:
```
[notice ] MediaServer: Initialized reference count of /home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/sources/videos/test.mov to 1
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_S_create
```

**Comment by martialgallorini** [comment]
i have similar issue : app crashes randomly when switching video source
i am on OSX with oF09


<img width="1395" alt="capture d ecran 2016-01-18 a 00 31 53" src="https://cloud.githubusercontent.com/assets/3931994/12380767/24a553f4-bd7b-11e5-9565-9df20c4b7673.png">

**Comment by kr15h** [comment]
yes, this is a weird issue that i have not found a solution for yet. thanks for reminding about it. although so far it happened only on the pi.

**Comment by martialgallorini** [comment]
yes seems it is not related to ofxOMXPlayer either though

i will try to dig a bit into it
