### ISSUE TITLE
On/off perspective warping for quad surfaces

### ISSUE THREAD

**Issue by kr15h** [kr15h/ofxPiMapper#22]
Ability to enable and disable perspective warping.

**Comment by magdesign** [comment]
How can I enable/disable perspective warping?
Or in other words: When I do a quad mask, it behaves like 2 triangle masks and not like a proper quad mesh. It gets a massive distortion line.
 Is there a trick to switch this?

**Comment by kr15h** [comment]
One way to do this is to use homography. There was a homograph.h file floating around the internet that has been made from the implementation OpenCV has. Meanwhile [this could be a good read](http://ramsrigoutham.com/2014/06/14/perspective-projection-with-homography-opencv/) for you.

**Comment by magdesign** [comment]
Ok, thanks.
Trying to figure out something, I have no experience in C coding.
Also found an interesting article: http://www.reedbeta.com/blog/2012/05/26/quadrilateral-interpolation-part-1/

**Comment by magdesign** [comment]
Sorry for the above post. 
Just found out that you already implemented everything in your code.

**Comment by kr15h** [comment]
Btw @magdesign - you are the one behind Pocket VJ?

**Comment by magdesign** [comment]
yes, its me :-)

https://github.com/magdesign/PocketVJ-CP-v2

**Comment by kr15h** [comment]
@magdesign nice job! The OMX sync and WiFi access point features are nice ones. Are you configuring the hostapd to spawn the PocketVJ interface on any request or one has to navigate to the index.php via IP address?

**Comment by magdesign** [comment]
Yes, you have to enter the IP address. 
There are also other possibilities, but when you want to surf the net on another tap, its the best solution. Maybe we should email or skype, rather than communicating here... 

I like PiMapper and its running smooth on the RPI2, I changed the code in QuadSurface.cpp to the commented one. Now the Quad mapping is nice, but there is an issue with the input texture selection.
Do you think you could fix this?

**Comment by kr15h** [comment]
Yes - it's on my to-do list. It might take some time time though there are some parallel things going on. First I want to deal with the Command design pattern implementation to make it possible to create OSC remote. I have not tried RPi 2 yet, but I believe that if piMapper already works on RPi 1 - no comments : ]

**Comment by martialgallorini** [comment]
Hello !

Also facing this problem...
@magdesign how did you fix this perspective issue ?

thanks a lot

**Comment by kr15h** [comment]
There is a commented block of code in the `QuadSurface.cpp`. Try to uncomment it. But as @magdesign  said - there is an issue with the texture coordinates. I am currently almost done with the architecture improvements and soon will be able to start tackling problems like this one.

**Comment by martialgallorini** [comment]
i uncommented this block 

	if(mesh.haveVertsChanged() || mesh.haveTexCoordsChanged()){
	    calculate4dTextureCoords();
	}
	
	glEnableClientState(GL_TEXTURE_COORD_ARRAY);
	glTexCoordPointer(4, GL_FLOAT, 0, quadTexCoordinates);
	glVertexPointer(3, GL_FLOAT, 0, quadVertices);

but with no luck

**Comment by martialgallorini** [comment]
ok above lines have to be un commented and those ones (just after) need to be commented

       source->getTexture()->bind();
       mesh.draw();
       source->getTexture()->unbind();

**Comment by kr15h** [comment]
Yes, that is what we are talking about here. Will try to do something about it as soon as possible.

**Comment by martialgallorini** [comment]
it would be much appreciated. thanks a lot
