### ISSUE TITLE
After loading the app on RPi 2, switch video sources then app crashes and this is the output:(3 case)

### ISSUE THREAD

**Issue by lanli** [kr15h/ofxPiMapper#29]
case1:                    
[notice ] MediaServer: Initialized reference count of /home/pi/of_v0.8.4_linuxarm7l_release/addon/ofxPiMapper/example/bin/data/sources/videos/test.mov to 1
Segmentation fault
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:168: recipe for target 'run' failed
make: ***[run]Error 139

case2:(sometime) 
[warning] bool ofxOMXPlayerEngine::setup(ofxOMXPlayerSettings&): FAST PATH MOVE OPEN FAILED - LIKELY A STREAM, TRYING SLOW PATH
[ error ] COMXPlayer::OpenFile - xxx......

case3:(enableAudio=true)
[ error ] COMXAudioCodecOMX::GetChannelMap - FFmpeg reported 2 channels, but the layout contains 0 ignoring
...

**Comment by kr15h** [comment]
Thanks for the feedback @lanli. Will look into that as soon as possible.

**Comment by kr15h** [comment]
Seems to be fixed now.
