### ISSUE TITLE
make: *** [run] Error 139 or 135

### ISSUE THREAD

**Issue by luisa20** [kr15h/ofxPiMapper#31]
I have two errors when I use an own new video source. What can I do?

**Comment by kr15h** [comment]
You should try re-encoding it. The following are the ecoding recomendations from ofxOMXPlayer:

 - Use MPEGStreamclip (http://www.squared5.com/)
 - H.264
 - Quality 50%
 - PCM Audio (more compatible with HDMI)

**Comment by luisa20** [comment]
Thanks!
I have try re-encoding. It did not work.
I copied the video in the folder: /home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/source/videos

**Comment by kr15h** [comment]
What is the full name of the video and would it be possible for you to send it to me to take a look?

**Comment by luisa20** [comment]
I have the video re-encoding again:
h.264 1280x720
24 fps
qualität 50%

now, it work!

Thanks for help!

2015-10-21 10:01 GMT+02:00 Krisjanis Rijnieks <notifications@github.com>:

**Comment by kr15h** [comment]
Great! Thanks for letting me know!
