### ISSUE TITLE
is there a way to boot at startup  directly to ofxpimapper in full screen ? (noobs question ...)

### ISSUE THREAD

**Issue by stephanebordonaro** [kr15h/ofxPiMapper#35]

**Comment by kr15h** [comment]
It seems that I have to add instructions on how to do this, but for now read the following.
`http://kr15h.github.io/RPi-Setup/index.html#titles.5.5`

And then in the `startup.sh` add a line that points to the compiled binary of your application (or ofxPiMapper example application).

**startup.sh**
```bash
#!/bin/bash

echo "Checking SSH connection...";
if [ -z "$SSH_CONNECTION" ]; then
	echo "No SSH connection, launching scripts.";
	/home/pi/openFrameworks/addons/ofxPiMapper/example/bin/example
else
	echo "SSH connection, nothing to be launched.";
fi
```
Before doing this it is essential that you run `make && make run` for your app.
```bash
cd /home/pi/openFrameworks/addons/ofxPiMapper/example
make && make run
```

Let me know if you have problems, will update this.

**Comment by stephanebordonaro** [comment]
Hi cool works great ! Thx 

Stéphane Bordonaro 
Créateur vidéo et lumière 
stephane.bordonaro@gmail.com
www.les4elements.com


-----Message d'origine-----
De : "Krisjanis Rijnieks" <notifications@github.com>
Envoyé : ‎20/‎12/‎2015 17:42
À : "kr15h/ofxPiMapper" <ofxPiMapper@noreply.github.com>
Cc : "stephanebordonaro" <stephane.bordonaro@gmail.com>
Objet : Re: [ofxPiMapper] is there a way to boot at startup  directly toofxpimapper in full screen ? (noobs question ...) (#35)

It seems that I have to add instructions on how to do this, but for now read the following.
http://kr15h.github.io/RPi-Setup/index.html#titles.5.5
And then in the startup.sh add a line that points to the compiled binary of your application (or ofxPiMapper example application).
startup.sh
#!/bin/bash

echo "Checking SSH connection...";
if [ -z "$SSH_CONNECTION" ]; then
    echo "No SSH connection, launching scripts.";
    /home/pi/openFrameworks/addons/ofxPiMapper/example/bin/example
else
    echo "SSH connection, nothing to be launched.";
fiBefore doing this it is essential that you run make && make run for your app.
cd /home/pi/openFrameworks/addons/ofxPiMapper/example
make && make runLet me know if you have problems, will update this.

**Comment by stephanebordonaro** [comment]
Hi ...thx for all This useful information.....i have also try to make it boot directly in full screen mode ... Changing things in the main prg is the right way ? I have try to force full screen ...without success ...

Stéphane Bordonaro 
Créateur vidéo et lumière 
stephane.bordonaro@gmail.com
www.les4elements.com


-----Message d'origine-----
De : "Krisjanis Rijnieks" <notifications@github.com>
Envoyé : ‎20/‎12/‎2015 17:42
À : "kr15h/ofxPiMapper" <ofxPiMapper@noreply.github.com>
Cc : "stephanebordonaro" <stephane.bordonaro@gmail.com>
Objet : Re: [ofxPiMapper] is there a way to boot at startup  directly toofxpimapper in full screen ? (noobs question ...) (#35)

It seems that I have to add instructions on how to do this, but for now read the following.
http://kr15h.github.io/RPi-Setup/index.html#titles.5.5
And then in the startup.sh add a line that points to the compiled binary of your application (or ofxPiMapper example application).
startup.sh
#!/bin/bash

echo "Checking SSH connection...";
if [ -z "$SSH_CONNECTION" ]; then
    echo "No SSH connection, launching scripts.";
    /home/pi/openFrameworks/addons/ofxPiMapper/example/bin/example
else
    echo "SSH connection, nothing to be launched.";
fiBefore doing this it is essential that you run make && make run for your app.
cd /home/pi/openFrameworks/addons/ofxPiMapper/example
make && make runLet me know if you have problems, will update this.

**Comment by kr15h** [comment]
You just pass the -f flag to the executable. I added faq with instructions about this today. https://github.com/kr15h/ofxPiMapper/blob/master/FAQ.md

**Comment by stephanebordonaro** [comment]
yeah ...things coming more clear to a " one week " raspberry user ...
i have seen things to hide the boot loader and replace the raspberry logo
by yours or any ...

thx for your work

2015-12-22 1:42 GMT+01:00 Krisjanis Rijnieks <notifications@github.com>:

> You just pass the -f flag to the executable. I added faq with instructions
> about this today. https://github.com/kr15h/ofxPiMapper/blob/master/FAQ.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kr15h/ofxPiMapper/issues/35#issuecomment-166467768>.
>



-- 
stephane.bordonaro@gmail.com
régie technique
tel : 06 03 26 69 31

https://www.linkedin.com/in/stephanebordonaro

 performance  vidéos
https://www.facebook.com/mapping.les4elements
www.les4elements.com
contact@les4elements.com

**Comment by kr15h** [comment]
I think that to replace the Raspberry logo you have to recompile the kernel. At least that's the latest information I found when I was thinking about the same.
