### ISSUE TITLE
can't build under OSX

### ISSUE THREAD

**Issue by martialgallorini** [kr15h/ofxPiMapper#37]
hello,

thanks for the addon
i have a problem : i can't make it to build under OSX El Capitan and oF09

see attached image 
<img width="1391" alt="capture d ecran 2016-01-15 a 11 58 38" src="https://cloud.githubusercontent.com/assets/3931994/12351762/86de19a4-bb80-11e5-81d3-ba5e924a3366.png">

any clue ?

**Comment by kr15h** [comment]
It is possible that you are missing dependencies. Did you install ofxUI?

**Comment by martialgallorini** [comment]
no ! i thought it was now using ofxGui ?

i will ha a try

**Comment by kr15h** [comment]
I think that even though ofxOMXPlayer is not used on Mac, you should download that as well. I will adjust the code so that is not the case. This is a good point.

**Comment by martialgallorini** [comment]
No chance using ofxUI
Also yes maybe a problem dealing with ofxOMXPlayer. I already had it installed though

**Comment by kr15h** [comment]
I will take a look a bit later today. It might be that there have to be some adjustments in the xcode project settings.

**Comment by martialgallorini** [comment]
ok thanks a lot.

here a screenshot in case it is of any help

<img width="1392" alt="capture d ecran 2016-01-15 a 14 36 27" src="https://cloud.githubusercontent.com/assets/3931994/12354328/7a7b2c82-bb95-11e5-92b8-15629fb4e993.png">

**Comment by kr15h** [comment]
Yeah it seems that it is trying to compile ofxOMXPlayer although xcode should not do it.

**Comment by kr15h** [comment]
Maybe you should remove ofxOMXPlayer from the xcode project tree. See what happens. Is it actually there?

**Comment by kr15h** [comment]
Another question - are you trying to build the example xcode project or are you building your own app?

**Comment by martialgallorini** [comment]
I will try with removing completely ofxOMXplayer.
i am trying to bbuild the exemple code

**Comment by kr15h** [comment]
yeah - the problem seems to be that on mac the regular openFrameworks video class is used. ofxOMXPlayer is used only when you compile the code on a Raspberry Pi.

**Comment by kr15h** [comment]
Please let me know if removing ofxOMXPlayer did work.

**Comment by martialgallorini** [comment]
ok, now it builds when ofxOMXPlayer is removed
but it doesn't seem to work properly : different modes seem to be the same

here are some logs if it helps

<img width="601" alt="capture d ecran 2016-01-16 a 12 21 30" src="https://cloud.githubusercontent.com/assets/3931994/12372113/55fd0832-bc4c-11e5-8a30-42335e31cc0b.png">

**Comment by kr15h** [comment]
So it compiles and runs. It seems that there is a file missing. What kind of sources are you trying to load?

**Comment by martialgallorini** [comment]
none ! just running the example

**Comment by kr15h** [comment]
Do you have anything in the `bin/data` folder of the project?

**Comment by martialgallorini** [comment]
yes, everything is in its right place...

**Comment by martialgallorini** [comment]
i cleaned the build and re-built it entirely. Now it seems to be better.
but always those errors in log
<img width="802" alt="capture d ecran 2016-01-16 a 13 09 58" src="https://cloud.githubusercontent.com/assets/3931994/12372329/796b688a-bc52-11e5-96e3-bc09c9d4c0b8.png">

**Comment by kr15h** [comment]
Don't worry about the errors. They are more as warnings. I probably should remove them to not cause confusion like this. It's just that loading the video takes some time and before it is loaded, the rendering loop is running. If the texture object to be rendered is empty (video not loaded), ofxPiMapper logs this error.

**Comment by martialgallorini** [comment]
perfect. Thanks a lot for your help and all your great work !
