### ISSUE TITLE
input source not accurate when quad perspective activated

### ISSUE THREAD

**Issue by martialgallorini** [kr15h/ofxPiMapper#38]
For the record : 

once quad perspective is activated, selecting an area in the input source view results in non consistent output : output doesn't reflect the area selected

**Comment by kr15h** [comment]
Yes, that's how the perspective warping works in a way. Try to select the whole texture as input. I will continue searching for alternatives and more precise solutions though. Can you post a screenshot here? I will open an issue with this.

**Comment by kr15h** [comment]
See #39

**Comment by martialgallorini** [comment]
great. Works perfectly now with homography implementation.
thanks a lot !

**Comment by kr15h** [comment]
Someone had to do it! : ]

**Comment by martialgallorini** [comment]
i would have if only i had the skills. but maths and i never happened to be the best friends back at school !
