### ISSUE TITLE
Once quad perspective is activated, selecting an area in the input source view results in non consistent output: output doesn't reflect the area selected

### ISSUE THREAD

**Issue by kr15h** [kr15h/ofxPiMapper#39]
In a way this is because of how perspective warping works. @aspeteRakete used a method described here http://www.reedbeta.com/blog/2012/05/26/quadrilateral-interpolation-part-1/

I wonder what MadMapper perspective warping looks like, will check it out. In my opinion, the perfect solution is a combination of mesh warping and perspective warping.

**Comment by martialgallorini** [comment]
here is some screenshots : 

Window size : 1280 x 720
Input size : 1280 x 720

Without perspective 
<img width="1318" alt="capture d ecran 2016-01-20 a 10 34 01" src="https://cloud.githubusercontent.com/assets/3931994/12444947/cbb62208-bf61-11e5-982d-727e3134e32c.png">


With perspective activated
<img width="1319" alt="capture d ecran 2016-01-20 a 10 34 35" src="https://cloud.githubusercontent.com/assets/3931994/12444955/d72ea51a-bf61-11e5-96aa-efd71cd9b745.png">

**Comment by martialgallorini** [comment]
Did you have a look at the ofxMtlMapping2D project ? It doesn't seem updated anymore but perspective warping seems to work there and maybe you could find some inspirations for perspective and/or other things

**Comment by kr15h** [comment]
Good idea. Will check that.

**Comment by martialgallorini** [comment]
ofxMtlMapping2D doesn't seem updated anymore but still builds in oF09 but crashes at some times. Interesting project though. I tried the perspective warping and it works great.

There is a dev branch which seems more advanced and more recent, but i couldn't make it build.

**Comment by kr15h** [comment]
it is using the `homography.h` by Arturo Castro. I was initially looking at this as a solution. Behold.

**Comment by martialgallorini** [comment]
yes, every project i had a test with uses openCV for the perspective correction or the homography.h from Arturo Castro as alternative. Arturo found this solution to prevent adding the whole openCV library just for the use of the perspective correction feature.

**Comment by kr15h** [comment]
Added homography helper. Works!
