### ISSUE TITLE
rpi2 - using mouse

### ISSUE THREAD

**Issue by martialgallorini** [kr15h/ofxPiMapper#41]
hello,

i was able to build piManager on a raspberry pi 2 under raspbian lite but without x11 i imagine i can't use the mouse right ?

so i installed openbox, but this doesn't work either...

how can i use the mouse on rpi ?

thanks a lot

**Comment by kr15h** [comment]
You can see the mouse only in the projection mapping and texture mapping modes. Although I plan to redesign the controls so you can use only keyboard or only mouse soon.

**Comment by martialgallorini** [comment]
ok great. I thought i tried mapping mode, but i must have made a mistake. 
it is working now.

thanks a lot for the help, and again, thanks a lot for this great project.
