### ISSUE TITLE
surface not consistent between window mode and fullscreen mode

### ISSUE THREAD

**Issue by martialgallorini** [kr15h/ofxPiMapper#45]
hello,

in window mode : add a quad and warp it

<img width="1219" alt="capture d ecran 2016-02-18 a 23 32 55" src="https://cloud.githubusercontent.com/assets/3931994/13160943/fe84c8d8-d69a-11e5-806d-29c562929e32.png">

go in fullscreen mode : image is scaling following the app window size instead of keeping inside the quad

<img width="1440" alt="capture d ecran 2016-02-18 a 23 33 11" src="https://cloud.githubusercontent.com/assets/3931994/13160974/2a5c5e58-d69b-11e5-8ac5-fa93d8ad8de6.png">

When clicking the surface to edit it, image texture resizes back to the quad surface

Image texture should follox the scale of the quad no matter we are toggling fullscreen or not

**Comment by kr15h** [comment]
This is interesting. Will take a look. Thanks.
