### ISSUE TITLE
Can I use an X Display as a source?

### ISSUE THREAD

**Issue by Taconut** [kr15h/ofxPiMapper#46]
I have a Raspberry Pi and a small pocket-sized projector and I'd like to be able to project my raspberry pi to any wall while correcting for keystone distortion. Is there any way to mirror my desktop using this program?

**Comment by kr15h** [comment]
It should work if you use 2 Raspberry Pi's - one booted up in desktop mode and another with [this](http://www.auvidea.eu/index.php/theme-styles/2014-12-30-22-32-06/b101) Raspberry Pi camera replacement board connected to it.

Like this:
![rpi-mapping-desktop](https://cloud.githubusercontent.com/assets/817241/13199676/0a2105de-d82c-11e5-8268-d177735bbc6f.jpg)

**Comment by Taconut** [comment]
Any single-device way to do it?

**Comment by kr15h** [comment]
No.

**Comment by Taconut** [comment]
Alright. I'll look into using an alternative solution and I'll keep the frame buffer idea in mind. Thanks.
