### ISSUE TITLE
Issue with deleting surface

### ISSUE THREAD

**Issue by awilkie1** [kr15h/ofxPiMapper#57]
When trying to remove a surface through SSH or main keyboard the surface cannot be deleted. Have tried a variety of ways including the latest version of PIMapper. Possibly because of a PI update ??

**Comment by kr15h** [comment]
Hi. I guess it's not implemented yet. The problem is that via SSH the backspace key does not work and thus I am trying to figure out what could be the replacement key.

**Comment by awilkie1** [comment]
Thanks for getting back to me. it also isnt working with the keyboard plugged in.

**Comment by kr15h** [comment]
Do the other shortcuts work? When you plug in the keyboard, you should restart the pi and the ofxPiMapper software for the keyboard to be properly recognised. Then go to mode 3, select a surface and hit BACKSPACE. Should work.

**Comment by awilkie1** [comment]
just tested it. All other shortcuts work apart from the back space. checked keyboard as well thats fine! Was working untill i did upgrade & update, so i guess some modification to raspbian have caused an issue?

**Comment by magdesign** [comment]
Please use 'd'  as replacement for backspace to delete surface... 
'a' for duplicate...
here a list of shortcuts I recommend (since its easier to simulate regular keys instead of special characters): https://github.com/magdesign/PocketVJ-CP-v3/files/188104/Keys_PocketVJ-VP-v3.pdf

**Comment by kr15h** [comment]
I have to think of a more decent replacement as the SSH remote anyway. It crashes sometimes. Not good. But a shortcut convention would be nice. I'd also prefer to use ctrl keys. ctrl+d most of the time is used for duplication. ctrl+a for select all. etc.

**Comment by awilkie1** [comment]
Ok great so its a key issue. i will change them in the project! Thanks

 p.s would be great to get TCPSyphon Client in there at some point as a input file

**Comment by kr15h** [comment]
Yes! TCPSyphon would be that awesome!

**Comment by kr15h** [comment]
By the way I see that via SSH one has to use "-" in order to delete. @awilkie1 did you try that?

**Comment by kr15h** [comment]
@magdesign I disagree with using 'd' for delete, the key is conventionally used in other software to duplicate. And I want to reserve 'a' for "select all" or similar.

**Comment by awilkie1** [comment]
Im not using ssh, just strait keyboard. However its become glitchy and sometimes works and sometimes not. I think adding some gui button would solve this within the application and would speed mapping up.

**Comment by kr15h** [comment]
Ah. OK. Will check that. Does your keyboard have a DEL button? Another shortcut would be "x" which is a delete button also in Blender. That could be an alternative.

**Comment by kr15h** [comment]
Are you still having problems?
