### ISSUE TITLE
copying the ofMesh every drawSelectedSurfaceHighlight

### ISSUE THREAD

**Issue by jvcleave** [kr15h/ofxPiMapper#58]
Not sure if `drawSelectedSurfaceHighlight` is called much but you may just want to return a reference

https://github.com/kr15h/ofxPiMapper/blob/master/src/Surfaces/SurfaceManagerGui.cpp#L290
https://github.com/kr15h/ofxPiMapper/blob/master/src/Surfaces/BaseSurface.h#L44

**Comment by kr15h** [comment]
Thanks for pointing out. Will look into this.
