### ISSUE TITLE
Refactor to avoid touching global GL states.

### ISSUE THREAD

**Issue by JoshuaBatty** [kr15h/ofxPiMapper#59]
Hi mate just trying to use your addon at the moment and have run into a problem. In your BaseSurface class you call ofEnableNormalisedTexCoords() and then I see that in your example you need to manually call ofDisableNormalisedTexCoords in each draw loop. Although this works in this instance I think it's best to avoid setting any GL global state within ofxPiMapper. It creates a lot of headaches to manually take care of what the current global GL state is when implementing the addon into larger projects. 

Do you have any thoughts on this? Cheers.

**Comment by kr15h** [comment]
Hey! Thanks for pointing out. Will try to look into that. Although `ofEnableNormalisedTexCoords()` is needed in order the texture mapping to work on the pi.

**Comment by kr15h** [comment]
Fixed. https://github.com/kr15h/ofxPiMapper/commit/c681e2e8b07033955c9f8210831aaad1b6ed3b17

**Comment by JoshuaBatty** [comment]
Awesome thanks dude i'll give this another run this week. Cheers.
