### ISSUE TITLE
Make interaction (request)

### ISSUE THREAD

**Issue by pietrondo** [kr15h/ofxPiMapper#68]
Hello, is possible to interact with the videos?
For example, with a keyboard start and stop a specific video? 

thx

**Comment by kr15h** [comment]
Will try to implement it in a simple way. Thanks for the request.

**Comment by kr15h** [comment]
So just added the possibility to play/pause a video source once a surface is selected by using SPACE bar. Enjoy!

**Comment by pietrondo** [comment]
ok thx.
Is possibile to "map" one specific surface with a button so you can play or stop with this specific button?

thx

**Comment by kr15h** [comment]
Nope, now it is that you have to select the specific surface to play/stop

**Comment by kr15h** [comment]
Well it is possible, but you have to add it to the source code. I will look into options how to make it configurable maybe.
