### ISSUE TITLE
Constrain quad surface texture selection to rect

### ISSUE THREAD

**Issue by kr15h** [kr15h/ofxPiMapper#7]
If you try to select a free-form quad as a texture for the quad surface it becomes ugly. To solve this a rect constraint is needed for the quad surface texture selector.

**Comment by stephanschulz** [comment]
I was wondering about this option; i.e. would it be possible to select a texture source that is not rectangular?
For example if one had a camera looking at a square but not straight on but rather from an angle. It would be great to only select this skewed square as source, which would produce a perfect square again.
Is that possible now?

**Comment by kr15h** [comment]
If you use two triangles, then yes

**Comment by stephanschulz** [comment]
I messed with the code a bit and removed this line
https://github.com/kr15h/ofxPiMapper/blob/ea851c83b19ea0ac257dfcb6d46bf8a34e0258c6/src/Gui/Widgets/TextureEditorWidget.cpp#L43

which disables the constrain. I can now see what you mean by "becomes ugly".
is there any way around this ugliness or is this a limit of openGL?
I guess one work around would be to do 2 passes of your mapping.
The first one would create a FBO that can be used to un-skew what the camera sees, and the second one will be used to project on to the wall.
