### ISSUE TITLE
how to control video inside example play stop pause

### ISSUE THREAD

**Issue by viniciolindo** [kr15h/ofxPiMapper#76]
i i cannot understand how to play and stop video with your example.
it is possible or not? what is the best way to do this?
thank's

**Comment by kr15h** [comment]
By pressing spacebar when in the texture editing and projection mapping modes. Press <3> first. Select a surface which has a video texture. Hit <SPACE>.

**Comment by viniciolindo** [comment]
it's possibile do that with code?  i need to do that with a sensor on arduino

**Comment by kr15h** [comment]
Hi! For now there is not a direct way, I will add it today/tomorrow. Will let you know.

**Comment by kr15h** [comment]
Added ofxPiMapper::togglePauseForSurface(unsigned int i) to the game. Try it out.
