### ISSUE TITLE
Command line build not working on mac after checkout

### ISSUE THREAD

**Issue by tilmans** [kr15h/ofxPiMapper#77]
The makefile will try to compile ofxOMXPlayer which won't work on mac (macos Sierra + of094). The build in XCode will work just fine. Maybe the README could mention that since I imagine a lot of people will first try to compile on their dev machine. 

Keep up the good work! 👍

**Comment by kr15h** [comment]
Yes. I should add that. Maybe there is a workaround. Will check.

**Comment by kr15h** [comment]
I think it is because the addon_config.mk file. It had ofxOMXPlayer as common addon dependencies, but ofxOMXPlayer is not common, it is only on Raspberry Pi. I removed it from the addon_config.mk. Please try again and let me know if it works for you now.

**Comment by tilmans** [comment]
works now, thank you!
