### ISSUE TITLE
Error to Compile new videos

### ISSUE THREAD

**Issue by fjrobles** [kr15h/ofxPiMapper#79]
<img width="749" alt="captura de pantalla 2016-10-31 a las 16 49 01" src="https://cloud.githubusercontent.com/assets/11178730/19858228/fcab58ba-9f80-11e6-9348-69d11e35e1e3.png">

I can´t compile new videos with new images everything is ok...

the modified file is ofxpimapper.xml, I changed: 

`<source-type>video</source-type>`
`<source-name>test.mov</source-name>`

I used predetermined sources. not new videos.

**Comment by kr15h** [comment]
I see you are using a mov file. The Raspberry Pi supports H264 encoding. You should encode your video to MP4. Also with an mp4 extension.

**Comment by fjrobles** [comment]
Sorry, but I tried all videos from ofxPiMapper/example/bin/data/sources/videos/.

<img width="848" alt="captura de pantalla 2016-11-01 a las 9 43 14" src="https://cloud.githubusercontent.com/assets/11178730/19882540/b79680e0-a00e-11e6-8d51-23a4da2fa53b.png">

![untitled-1](https://cloud.githubusercontent.com/assets/11178730/19882551/ca256780-a00e-11e6-956b-ca1993b4f355.png)

**Comment by kr15h** [comment]
I see there is a missing </surface> closing tag just after <properties></properties>

**Comment by kr15h** [comment]
In his case the video is not the problem, but the validity of the xml file. The application fails to parse it as it is malformed.

**Comment by fjrobles** [comment]
I have validate the XML file but still doesnt work... Actually the screen appear totally white

<img width="848" alt="captura de pantalla 2016-11-01 a las 11 39 53" src="https://cloud.githubusercontent.com/assets/11178730/19885454/f27a910a-a01e-11e6-8c7a-714b8f9b4ac3.png">

**Comment by kr15h** [comment]
It might be the Raspberry Pi memory split at this point. Try to increase the amount of the memory consumed by the GPU by opening the config tool with `sudo raspi-config`, go to Advanced Settings and Memory Split. Enter 256 there, save and exit. Reboot.

**Comment by fjrobles** [comment]
Yes!!!!!! the problem was Memory Split!!!!! Thanks a lot!!!!!!!

**Comment by kr15h** [comment]
Cool! : ] Good luck with the rest then. Just ask if there are more problems/bugs. One shalt close this issue now....
