### ISSUE TITLE
Mesh warping for quad surface

### ISSUE THREAD

**Issue by kr15h** [kr15h/ofxPiMapper#8]
Add possibility to add multiple rows and columns to the quad surface.

**Comment by magdesign** [comment]
maybe also bezier warp function for quads (to use on round surfaces...):
https://github.com/TsubokuLab/ofxBezierWarpManager

**Comment by kr15h** [comment]
does it work on pi?

-----Original Message-----

**Comment by magdesign** [comment]
Will test it and let you know,
there are some apps which would be very cool for running on pi:

- https://github.com/TsubokuLab/ofxBezierWarpManager
- https://github.com/frauzufall/ofx2DMapping
- https://github.com/TsubokuLab/ofxContrast
- https://github.com/microcosm/ofxProjectionMask

its on my roadmap....

**Comment by kr15h** [comment]
Yes
