### ISSUE TITLE
ofxIO issue 

### ISSUE THREAD

**Issue by awilkie1** [kr15h/ofxPiMapper#86]
Just a quick one. They have upgraded ofxIO meaning the current version doesn't run with pi mapper. Found if I downgraded ofxIO 9.0 it worked fine. A possible update of pi mapper to accommodate the new ofxIO would be great! Thanks

**Comment by kr15h** [comment]
I think you just go to `addons/ofxIO` and `git checkout stable`. Recompile. Should work.

**Comment by kr15h** [comment]
On the other hand, I want to get rid of this dependency. More is less dependencies. This issue is messing up the minds of too many users lately.

**Comment by awilkie1** [comment]
i have it working now on a lower version of ofxIO but yeah would be great to fix or remove it as a dependency. Thanks for the support!

**Comment by awilkie1** [comment]
Sorry to re-open the issue however thought I would update you on this one. tried running with all current stable versions of addons as you said a got this error any ideas ??
![screen shot 2017-01-23 at 15 45 04](https://cloud.githubusercontent.com/assets/5709260/22210818/f648f29a-e182-11e6-8feb-c9346b8c258c.png)

**Comment by kr15h** [comment]
weird. will look into this...

**Comment by janisso** [comment]
Getting similar error when trying to make example code.
I am using RPi 3 with OF 0.9.8 for armv6l with Jesse Pixel

/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:200: recipe for target 'obj/linuxarmv6l/Release/src/main.o' failed
make[1]: *** [obj/linuxarmv6l/Release/src/main.o] Error 1
make[1]: Leaving directory '/home/pi/openFrameworks/addons/ofxPiMapper/example'
/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:125: recipe for target 'Release' failed

**Comment by kr15h** [comment]
You should use the `stable` branch of the ofxPiMapper repository since I introduced changes in the repo structure. Now the master branch is developed to match the openFrameworks `master` branch. ofxIO is removed in the current stable branch and it should not cause problems when compiling.

**Comment by janisso** [comment]
Awesome! Paldies!

**Comment by kr15h** [comment]
There is no ofxIO dependency anymore.
